// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDhvFGVca-aLT5LZJWma0jV9IFjhrovf8',
    appId: '1:563379077533:web:6e8ae10d13741a4ce06f74',
    messagingSenderId: '563379077533',
    projectId: 'smart-cane-prototype',
    authDomain: 'smart-cane-prototype.firebaseapp.com',
    storageBucket: 'smart-cane-prototype.firebasestorage.app',
    measurementId: 'G-3PQZQRRMFS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqyK9VvOmbLN-AeJdx8vVM7AwmqPBAAhg',
    appId: '1:563379077533:android:22900ad0b861eff4e06f74',
    messagingSenderId: '563379077533',
    projectId: 'smart-cane-prototype',
    storageBucket: 'smart-cane-prototype.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZW-OBkc2ZCjnLFzEhHd17vOt5gTFaM5Y',
    appId: '1:563379077533:ios:06c99260870e2b0fe06f74',
    messagingSenderId: '563379077533',
    projectId: 'smart-cane-prototype',
    storageBucket: 'smart-cane-prototype.firebasestorage.app',
    iosBundleId: 'com.sept.learningfactory.smartCanePrototype',
  );
}
